backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: static/images
public_folder: images
collections:
  - name: "arquitectos"
    label: "Arquitectos"
    folder: "content/arquitectos"
    create: true
    fields:
      - {label: "Id", name: "id", widget: "hidden", default: "arquitecto_{{hour}}{{minute}}{{second}}"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Nationality", name: "nationality", widget: "string"}
      - {label: "Birth_year", name: "birth_year", widget: "number"}
      - {label: "Fields", name: "fields", widget: "select", multiple: true,
         options: ["Arquitectura moderna", "Arquitectura contemporanea", "Arquitectura basica",
          "Compilers","Data Structures"]}
      - {label: "Image", name: "image", widget: "image",
           media_folder: '/static/images/arquitectos'}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "ciudades"
    label: "Ciudades"
    folder: "content/ciudades"
    create: true
    fields:
      - {label: "Id", name: "id", widget: "hidden", default: "ciudad_{{hour}}{{minute}}{{second}}"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Country", name: "country", widget: "string"}
      - {label: "Founded", name: "founded", widget: "number"}
      - {label: "Image", name: "image", widget: "image",
           media_folder: '/static/images/ciudades'}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "edificios"
    label: "Edificios"
    folder: "content/edificios"
    create: true
    fields:
      - {label: "Id", name: "id", widget: "hidden", default: "book_{{hour}}{{minute}}{{second}}"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Founded", name: "founded", widget: "number"}
      - {label: "High", name: "high", widget: "string"}
      - {label: "Arquitecto", name: "arquitectoId", widget: "relation",
          collection: "arquitectos", search_fields: ["name"], value_field: "id",
          display_fields: ["name"]}
      - {label: "Ciudad", name: "ciudadId", widget: "relation",
          collection: "ciudades", search_fields: ["name"], value_field: "id",
          display_fields: ["name"]}
      - {label: "Image", name: "image", widget: "image",
           media_folder: '/static/images/edificios'}
      - {label: "Body", name: "body", widget: "markdown"}